### ISSUE TITLE
Payload for payment eligibility method does not work according to demo code

### ISSUE THREAD

**Issue by k3z** [alma/alma-python-client#13]
This sample code not working for me

```payment_data = {
    "purchase_amount": 10000,
    "return_url": "http://merchant.com/payment-success",
    "shipping_address": {
        "first_name": "Martin",
        "last_name": "Dupond",
        "line1": "1 rue de Rivoli",
        "postal_code": "75004",
        "city": "Paris"
    }
}

eligibility = alma_client.payments.eligibility(payment_data)
```

Response

```
{'constraints': {'purchase_amount': {'maximum': 200000, 'minimum': 10000}},
 'eligible': False,
 'installments_count': 3,
 'reasons': {'purchase_amount': 'missing_field'}}
```

I had to wrap my payload into `payment` property.

`eligibility = alma_client.payments.eligibility({'payment': payment_data})`

This is a little disturbing when a coder starts.

I also suggest adding a link to the official API documentation.

Thank you,

**Comment by olance** [comment]
@k3z sorry for the delayed reply...
You are right, thanks for pointing it out! I just fixed the README code, we'll hade more documentation / links to our API reference in a separate PR 🙂
