### ISSUE TITLE
Type problem on the start and end parameter

### ISSUE THREAD

**Issue by axelcroce** [alma/alma-python-client#23]
When creating a data export, the _start_ and _end_ parameter are expecting **datetime** values :
![image](https://user-images.githubusercontent.com/46299519/168020898-5bd627a5-2252-4da2-b909-15beb03a3232.png)

But when I give _start_ and _end_ as **datetime**, I get this error : 
`
formated_date_begin = datetime.strptime(date_begin_yyyymmdd, "%Y%m%d")
`
`
formated_date_end = datetime.strptime(date_end_yyyymmdd, "%Y%m%d")
`
![image](https://user-images.githubusercontent.com/46299519/168021908-0bc5575d-fa07-4ade-b06a-4ed7690f5780.png)

When I give _start_ and _end_ as **string** in this format : "YYYY-MM-DD", I get this error :
`
formated_date_begin = datetime.strptime(date_begin_yyyymmdd, "%Y%m%d").strftime("%Y-%m-%d")
`
`
formated_date_end = datetime.strptime(date_end_yyyymmdd, "%Y%m%d").strftime("%Y-%m-%d")
`
![image](https://user-images.githubusercontent.com/46299519/168022264-acaf5b84-b75e-4182-a5f4-4df92573c0f8.png)

And when I give _start_ as a string and _end_ as a datetime, the code runs well but the end date isn't taken into account and the export contains all the payments since the start date.
`
formated_date_begin = datetime.strptime(date_begin_yyyymmdd, "%Y%m%d").strftime("%Y-%m-%d")
`
`
formated_date_end = datetime.strptime(date_end_yyyymmdd, "%Y%m%d")
`

**Comment by elemoine** [comment]
Hi @axelcroce! The data-export endpoint expects Unix timestamps.

In python, you can use:
```py
from datetime import datetime

start = datetime(year=2022, month=5, day=13).timestamp()
```

**Comment by axelcroce** [comment]
Hi @elemoine, the main problem is that the end date isn't taken into account and the export contains all the payments since the start date.

**Comment by elemoine** [comment]
@axelcroce there may be a bug :thinking: Can you please confirm that you're trying to do a `payments` export? And what is the `end` date you're trying to use?

**Comment by axelcroce** [comment]
@elemoine Yes I'm creating a **payments** export with the following dates : 
start = 2022-05-05 (in string : **'2022-05-05'** otherwise it doesn't work)
end = 2022-05-06  (in datetime : **datetime.datetime(2022, 5, 6, 0, 0)** )

**Comment by elemoine** [comment]
@axelcroce as said above `start` and `end` should be timestamps (in seconds).

**Comment by elemoine** [comment]
@axelcroce maybe you could give us more context, with the Python code you use.

**Comment by axelcroce** [comment]
@elemoine, it doesn't work when start and end are **timestamps**. The only way the code runs correctly is when start is a string and end is a datetime. 
I have a **collect** function that takes the start date and end date as parameter. This function will create the data export by calling an other function called **_create_data_export()** 

`
        
        def collect(self, export_directory: str, dataset_id: str, table_id: str, date_begin_yyyymmdd: str, date_end_yyyymmdd: str, decoder_data_flag: bool=False):
        """Creates a Data Export then write the content into a csv file using the Alma API
        Args:
            export_directory (str): root directory
            dataset_id (str): name of dataset usecase
            table_id (str): name of table usecase
            date_begin_yyyymmdd (str): start date of the use case in YYYYMMDD format
            date_end_yyyymmdd (str): end date of the use case in format YYYYMMDD format
            decoder_data_flag (bool): if the data needs to be geocoded
        """

        formated_date_begin = datetime.strptime(date_begin_yyyymmdd, "%Y%m%d").strftime("%Y-%m-%d")
        formated_date_end = datetime.strptime(date_end_yyyymmdd, "%Y%m%d").timestamp()

        # Create Data Export
        data_export_id = self._create_data_export(self.__export_type, formated_date_begin, formated_date_end)

        # Polling the endpoint until export is ready
        completed_export = False
        while not completed_export:
            completed_export = self.__alma_client.exports.fetch(data_export_id)._data["complete"]
            time.sleep(5)

        self.__logger.info("Data Export {data_export_id} ready to collect.".format(
            data_export_id = data_export_id
        ))

        # Get buffer from data export
        file_object, file_extension = self._get_dataexport(data_export_id, self.__export_format)

        #Write to file
        save_path = self._build_export_file_path(export_directory, dataset_id, table_id, date_begin_yyyymmdd, date_end_yyyymmdd, file_extension)
        os.makedirs(os.path.dirname(save_path), exist_ok=True)

        self._write_to_file(save_path, file_object)
`
`

    def _create_data_export(self, export_type: str, start, end, include_child_accounts: bool=False):
        """Creates a data export using the alma Python client

        Args:
            export_type(str): Type of the dataexport to create (payments, pos_export, statement, accounting, accounting_for_payout)
            include_child_accounts(str): Whether the export should include data from
            start (str): Start date of the use case in YYYYMMDD format
            end (datetime): End date of the use case in datetime format

        Yields:
            export_id: str
        """
        if export_type == "payments":
            export = self.__alma_client.exports.create(ExportType.PAYMENTS, start, end)
        elif export_type == "accounting":
            export = self.__alma_client.exports.create(ExportType.ACCOUNTING, start, end)
        elif export_type == "accounting_for_payout":
            export = self.__alma_client.exports.create(ExportType.ACCOUNTING_FOR_PAYOUT, start, end)
        else:
            self.__logger.error("Wrong export type. {export_type} is not supported".format(
                export_type = export_type
            ))
            raise ValueError("Wrong export type. For now, only payments exports are supported")

        self.__logger.info("Export {export_id} of type {export_type} successfully created".format(
            export_id=export._data["id"],
            export_type = export_type
        ))

        return export._data["id"]

`

- When I give **timestamps** for **start and end**, the code fail with the following error : 
![image](https://user-images.githubusercontent.com/46299519/169253058-517438fd-b960-4748-82a9-5bbabe0f4f97.png)
- When I give **start** as **timestamp** and **end** as **datetime**, **it works but the file contains all the payments since the start date**

**Comment by axelcroce** [comment]
@elemoine  So I believe there is a problem on the type expected for the end parameter, or at least a problem on how the end parameter is taken into account.

**Comment by elemoine** [comment]
@elemoine ok my mad, I didn't know that the client code converted the inputs into timestamps before sending them to the API endpoint. I'll look further. Thank you for your patience.

**Comment by elemoine** [comment]
The signature of the `Exports.create` function is the following:

https://github.com/alma/alma-python-client/blob/73088c86ffe6ac8adbe688001c000959e4404c29/alma/endpoints/exports.py#L12-L18

So the second argument, after the `export_type`, is the `payout_id`. If you don't have any `payout_id` you can do this:

```py
export = self.__alma_client.exports.create(ExportType.PAYMENTS, start=start, end=end)
```

(Note the use of named arguments!)

And, as you can see in the function signature, `start` and `end` are `datetime` objects. Very sorry about the confusion about this.

Hope it'll work for you this time!

**Comment by axelcroce** [comment]
@elemoine, 
It finally works !
Thanks for your answer, I think the source of the problem was that I didn't use named arguments !

**Comment by elemoine** [comment]
@axelcroce yes exactly! Glad that it now works!
